# Use MySQL image
FROM mysql:8.0

# Set root password for MySQL
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=urban_connect

# Expose MySQL port
EXPOSE 3306

# Copy SQL file to Docker container
COPY ./init.sql /docker-entrypoint-initdb.d/
